version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
    command: bash -c "airflow db init"
    user: "0"
    volumes:
      - /Users/lupeipei/PycharmProjects/data-flow/dags:/opt/airflow/dags
      - /Users/lupeipei/PycharmProjects/data-flow/requirements.txt:/opt/airflow/requirements.txt

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - mysql
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'a_very_secret_key'
      AIRFLOW__CORE__FERNET_KEY: ''
    ports:
      - "8080:8080"
    command: bash -c "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow webserver"
    volumes:
      - /Users/lupeipei/PycharmProjects/data-flow/dags:/opt/airflow/dags
      - /Users/lupeipei/PycharmProjects/data-flow/producers:/opt/airflow/producers
      - /Users/lupeipei/PycharmProjects/data-flow/spark_jobs:/opt/airflow/spark_jobs
      - /Users/lupeipei/PycharmProjects/data-flow/consumers:/opt/airflow/consumers
      - /Users/lupeipei/PycharmProjects/data-flow/requirements.txt:/opt/airflow/requirements.txt
      - /Users/lupeipei/PycharmProjects/data-flow/logs:/opt/airflow/logs

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - mysql
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
    command: bash -c "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow scheduler"
    volumes:
      - /Users/lupeipei/PycharmProjects/data-flow/dags:/opt/airflow/dags
      - /Users/lupeipei/PycharmProjects/data-flow/producers:/opt/airflow/producers
      - /Users/lupeipei/PycharmProjects/data-flow/spark_jobs:/opt/airflow/spark_jobs
      - /Users/lupeipei/PycharmProjects/data-flow/consumers:/opt/airflow/consumers
      - /Users/lupeipei/PycharmProjects/data-flow/requirements.txt:/opt/airflow/requirements.txt
      - /Users/lupeipei/PycharmProjects/data-flow/logs:/opt/airflow/logs

volumes:
  mysql_data:
  kafka_data:
  es_data: